### PR TITLE
Some fixes to make kernel work with latest Jupyter

### PR DESCRIPTION
**Pull request by signalpillar**
Hi, I've did several changes in iocaml to make it work with latest Jupyter.

5 commits cover the following: 
- updated type for `execute_request`
- updated type for `complete_request` 
- added stub to not fail on opening mechanism for custom messages
- fix the build (travis)
- add documentation how to test manually

I am a newbie in the OCaml world so please point me if something need to be changed. 

All these fixes I used to [build a docker image](https://github.com/signalpillar/ocaml-playground) that serves Jupyter with iocaml kernel configured.

### CODE REVIEW

**Comment by andrewray** [comment]
Hey thanks for this!

A few people now have asked about Iocaml and Jupyter.

I need to make sure this works with iocamlserver+opam before integration, but apart from that I intend to merge this.

Could you perhaps provide some instructions for testing the Jupyter notebook with iocaml either here or in an issue?

**Comment by signalpillar** [comment]
@andrewray thanks! sure I will add instructions how I tested this on my mac + the Dockerfile project I mentioned in the issue description can be used for testing, I used it mostly.

**Comment by signalpillar** [comment]
@andrewray I've added `CONTRIBUTING.md` which describes how to test manually. 

It would be cool to update it later with the following

- style guides
- how to run tests automatically 
- how to contribute (what is expected from PR)

Another thing I try to get travis green. So far, I've updated dependency on newer OCaml and Opam version. The same I used on Ubuntu and on my dev machine (OS X). 
And it fails on `ocamlfind: Package `ctypes.foreign.unthreaded' not found - required by `types.foreign'`

**Comment by andrewray** [comment]
Thanks for that.  I will work through it over the weekend.

Sorry about the travis testing - it's bitrotted a bit (again!).  I'll see what I can do.

**Comment by signalpillar** [comment]
When we have a PPA for last OPAM do we need this in our travis script 
`opam remote add iocaml-dev git://github.com/andrewray/opam.git` ?

**Comment by andrewray** [comment]
I dont think so - the idea is to install infrastructure (like ubuntu and opam) then build within a travis copy of the github repo.  The scripts are a bit subtle (taken from general opam testing stuff a while ago) and need updating.

**Comment by signalpillar** [comment]
Ok, understood! script is very clear and good just need to be updated. I'm looking at it now

**Comment by andrewray** [comment]
I wouldn't worry too much about Travis.

The big test is to make it work with iocamlserver to be honest.  It shouldn't be hard (just ignore a few messages it's not interested in - yet!).

**Comment by signalpillar** [comment]
It would be nice if you can share this weekend how you test it with "iocamlserver" :)

**Comment by andrewray** [comment]
Install it with `opam install iocaml` (which gets the server and kernels) then fix problems with 'iocaml -v -v ...'.  Not very advanced really!.

**Comment by andrewray** [comment]
ocaml/opam-repository#5317

merges this and a number of general updates to the iocaml tools.

Hopefully you should now be able to use Jupyter with `iocaml-kernel` installed with `opam`.

Thanks again for the patches.

**Comment by signalpillar** [comment]
@andrewray superb! 

Have you experienced issues with highlighting ? I didn't investigate yet, but I see only initially loaded cells as highlighted but new are not.

**Comment by andrewray** [comment]
I see the same thing as you regarding highlighting.  I remember something about this from ihaskell

https://github.com/gibiansky/IHaskell/blob/master/html/kernel.js

but I'm not totally sure what it's all about.

**Comment by signalpillar** [comment]
Ok, thank you

**Pull request merged**
